# -*- coding: utf-8 -*-
"""comparison.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19v_UCFi83Nrx-_wQ8-lhxm7-C4jWzX3f
"""

!pip install -q jieba scikit-learn google-generativeai

import math
import jieba
import re
import json
from collections import Counter
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import google.generativeai as genai
from google.colab import userdata # Colab 環境專用，用於讀取密鑰
API_KEY = userdata.get("GOOGLE_API_KEY")
genai.configure(api_key=API_KEY)

# --- 傳統方法 (TF-IDF 相似度) ---

def calculate_tf(word_dict, total_words):
    """計算詞頻 TF"""
    tf_dict = {}
    for word, count in word_dict.items():
        tf_dict[word] = count / total_words
    return tf_dict

def calculate_idf(documents, word):
    """計算逆文件頻率 IDF"""
    N = len(documents)
    containing_docs = sum(1 for doc in documents if word in doc)
    return math.log(N / (1 + containing_docs)) + 1

def cosine_sim(doc1, doc2):
    """計算兩個 TF-IDF 向量的餘弦相似度"""
    words = set(doc1.keys()).union(set(doc2.keys()))
    v1 = [doc1.get(w, 0) for w in words]
    v2 = [doc2.get(w, 0) for w in words]
    dot = sum(a*b for a, b in zip(v1, v2))
    norm1 = math.sqrt(sum(a*a for a in v1))
    norm2 = math.sqrt(sum(a*a for a in v2))
    return dot / (norm1 * norm2) if norm1 * norm2 != 0 else 0


# --- 傳統方法 (基於規則的分類器) ---
#情感分類器
class RuleBasedSentimentClassifier:
    def __init__(self):
        # 正面詞庫 + 同義詞
        self.positive_words = ['好','棒','優秀','喜歡','推薦','滿意','開心','值得','精彩','完美','好吃','美味','驚艷','提升',"進步"]
        # 負面詞庫 + 同義詞
        self.negative_words = ['差','糟','失望','討厭','不推薦','浪費','無聊','爛','糟糕','差勁','空洞','疲勞','痛苦']
        # 否定詞
        self.negation_words = ['不','沒','無','非','別']
        # 程度副詞加權
        self.intensifiers = {'非常':1.5, '挺':1.1, '超':1.3}

    def classify(self, text):
        pos_score = 0
        neg_score = 0
        tokens = list(jieba.cut(text))

        i = 0
        while i < len(tokens):
            word = tokens[i]
            weight = 1
            # 程度副詞
            if i > 0 and tokens[i-1] in self.intensifiers:
                weight = self.intensifiers[tokens[i-1]]
            # 否定詞
            negation = False
            if i > 0 and tokens[i-1] in self.negation_words:
                negation = True
            if word in self.positive_words:
                if negation:
                    neg_score += 1 * weight
                else:
                    pos_score += 1 * weight
            elif word in self.negative_words:
                if negation:
                    pos_score += 1 * weight
                else:
                    neg_score += 1 * weight
            i += 1

        if pos_score > neg_score:
            return '正面'
        elif neg_score > pos_score:
            return '負面'
        else:
            return '中性'
#主題分類器
class TopicClassifier:
    def __init__(self):
        self.topic_keywords = {
            '科技': ['AI', '人工智慧', '電腦', '軟體', '程式', '演算法', '深度學習', '模型'],
            '運動': ['運動', '健身', '跑步', '游泳', '球類', '比賽', '慢跑', '重訓', '體能'],
            '美食': ['吃', '食物', '餐廳', '美味', '料理', '烹飪', '牛肉麵', '湯頭', '麵條'],
            '旅遊': ['旅行', '景點', '飯店', '機票', '觀光', '度假', '旅遊']
        }

    def classify(self, text):
        tokens = list(jieba.cut(text))
        counts = {topic: sum(1 for t in tokens if t in keywords) for topic, keywords in self.topic_keywords.items()}
        max_count = max(counts.values())
        if max_count == 0:
            return '其他'
        # 返回計數最高的那個主題
        return max((topic for topic, count in counts.items() if count == max_count), default='其他')


# --- 傳統方法 (統計式自動摘要) ---

class StatisticalSummarizer:
    def __init__(self):
        self.stop_words = set([
            '的','了','在','是','我','有','和','就','不','人','都','一','一個','上','也','很','到','說','要','去','你'
        ])

    def sentence_score(self, sentence, word_freq, position, total_sentences):
        tokens = [w for w in jieba.cut(sentence) if w not in self.stop_words and len(w.strip())>0]
        score = sum(word_freq.get(w,0) for w in tokens)
        if position == 0 or position == total_sentences-1:
            score *= 1.2
        if len(tokens) < 5:
            score *= 0.8
        if re.search(r'\d', sentence) or re.search(r'[A-Z]{2,}', sentence):
            score *= 1.1
        return score

    def summarize(self, text, ratio=0.3):
        sentences = re.split(r'(?<=[。！？\n])', text)
        sentences = [s.strip() for s in sentences if len(s.strip())>0]
        words = [w for s in sentences for w in jieba.cut(s) if w not in self.stop_words and len(w.strip())>0]
        word_freq = Counter(words)
        scores = []
        total_sentences = len(sentences)
        for idx, sentence in enumerate(sentences):
            score = self.sentence_score(sentence, word_freq, idx, total_sentences)
            scores.append((sentence, score))
        top_n = max(1, int(len(sentences)*ratio))
        top_sentences = sorted(scores, key=lambda x: x[1], reverse=True)[:top_n]
        top_sentences_sorted = sorted(top_sentences, key=lambda x: sentences.index(x[0]))
        return ' '.join([s[0] for s in top_sentences_sorted])


# --- 現代 AI 方法 (Gemini) ---

def ai_similarity(text1, text2, api_key):
    """使用 Gemini Pro 模型計算語意相似度 (0-100 分)"""
    if not api_key: return "N/A (API Key Missing)"
    try:
        model = genai.GenerativeModel("gemini-2.5-flash-lite")
        prompt = f"""
        請評估以下兩段文字的語意相似度。請僅輸出一個整數分數（0-100）。
        文字1：{text1}
        文字2：{text2}
        """
        response = model.generate_content(prompt)
        result = response.text.strip()
        score = int(''.join([c for c in result if c.isdigit()]))
        return min(100, max(0, score))
    except Exception as e:
        return f"Error: {e}"

def ai_classify_gemini(text):
    """使用 Gemini 2.5 Flash Lite 進行多維度文本分類"""
    if not API_KEY: return {"error": "N/A (API Key Missing)"}
    prompt = f"""
    請閱讀以下文字，判斷它的「情感傾向」與「主題類別」。

    文字：
    {text}

    請以 JSON 格式回答，鍵名為 sentiment (正面/負面/中性) 和 topic (主題類別)。
    請只輸出 JSON，不要額外文字。
    """
    model = genai.GenerativeModel("gemini-2.5-flash-lite")
    try:
        response = model.generate_content(prompt)
        result_text = response.text.strip()
        cleaned = re.sub(r"```json|```", "", result_text).strip()
        return json.loads(cleaned)
    except Exception as e:
        return {"error": f"AI Classification Error: {e}"}

def ai_summarize(text, max_length=150):
    """使用 Gemini-2.5-flash-lite 生成自動摘要"""
    if not API_KEY: return "N/A (API Key Missing)"
    model = genai.GenerativeModel(model_name="gemini-2.5-flash-lite")
    prompt = f"""
    請將以下文章摘要成一段流暢、通順的中文文字。
    摘要要求：盡量控制摘要長度約{max_length}個字。
    文章：
    {text}
    """
    try:
        response = model.generate_content(prompt)
        return response.text.strip()
    except Exception as e:
        return f"Error: {str(e)}"

# 執行比較測試

def run_comparison():
    print("🌟 傳統 NLP 方法 vs 現代 AI 方法比較 🌟")
    print("========================================\n")

    # 1. 文本相似度比較
    print("--- 1. 文本相似度 (Doc1: 人工智慧正在改變世界,機器學習是其核心技術) ---")
    documents_raw = [
    "人工智慧正在改變世界,機器學習是其核心技術",
    "深度學習推動了人工智慧的發展,特別是在圖像識別領域",
    "今天天氣很好,適合出去運動",
    "機器學習和深度學習都是人工智慧的重要分支",
    "運動有益健康,每天都應該保持運動習慣"
    ]
    doc1, doc2, doc3, doc4, doc5 = documents_raw[0], documents_raw[1], documents_raw[2], documents_raw[3], documents_raw[4]

    # TF-IDF (scikit-learn)
    def tfidf_similarity(docs, target_idx=0):
        # 進行分詞以配合 TF-IDF
        tokenizer = lambda text: list(jieba.cut(text))
        vectorizer = TfidfVectorizer(tokenizer=tokenizer)
        tfidf_matrix = vectorizer.fit_transform(docs)
        cos_sim = cosine_similarity(tfidf_matrix[target_idx:target_idx+1], tfidf_matrix)
        # 返回與 Doc1 的相似度，排除與自己的相似度 (cos_sim[0][0])
        return [f"{sim:.4f}" for sim in cos_sim[0][1:]]

    tfidf_results = tfidf_similarity(documents_raw)

    # 輸出比較結果
    print(f"Doc1 vs Doc2 (AI, DL): \tTF-IDF = {tfidf_results[0]}, AI = {ai_similarity(doc1, doc2, API_KEY)}")
    print(f"Doc1 vs Doc3 (AI, Weather): \tTF-IDF = {tfidf_results[1]}, AI = {ai_similarity(doc1, doc3, API_KEY)}")
    print(f"Doc1 vs Doc4 (AI, ML): \tTF-IDF = {tfidf_results[1]}, AI = {ai_similarity(doc1, doc4, API_KEY)}")
    print(f"Doc1 vs Doc5 (AI, Exercise): \tTF-IDF = {tfidf_results[1]}, AI = {ai_similarity(doc1, doc5, API_KEY)}")
    print("\n* 觀察：AI 模型在捕捉語義關聯方面表現更佳，畢竟機器學習不只是單純的詞彙計數。")

    print("\n" + "="*40 + "\n")

    # 2. 文本分類比較
    print("--- 2. 文本分類 (情感與主題) ---")
    test_samples = [
        "這家餐廳的牛肉麵真的太好吃了,湯頭濃郁,麵條Q彈,下次一定再來!",
        "最新的AI技術突破讓人驚艷,深度學習模型的表現越來越好",
        "這部電影劇情空洞,演技糟糕,完全是浪費時間",
        "每天慢跑5公里,配合適當的重訓,體能進步很多",
    ]
    sentiment_clf = RuleBasedSentimentClassifier()
    topic_clf = TopicClassifier()

    for i, text in enumerate(test_samples):
        print(f"\n[文本 {i+1}] {text}")

        # 傳統方法
        rule_sent = sentiment_clf.classify(text)
        rule_topic = topic_clf.classify(text)
        print(f"  傳統規則：情感 = {rule_sent}, 主題 = {rule_topic}")

        # 現代 AI 方法
        ai_result = ai_classify_gemini(text)
        if 'error' not in ai_result:
            print(f"  現代 AI：情感 = {ai_result.get('sentiment')}, 主題 = {ai_result.get('topic')}")
        else:
            print(f"  現代 AI：{ai_result['error']}")

    print("\n* 觀察：AI 分類器在處理複雜語境或未登錄詞彙時，通常更為準確（假設它的訓練數據夠好）。")

    print("\n" + "="*40 + "\n")

    # 3. 自動摘要比較
    print("--- 3. 自動摘要 ---")
    article = """
人工智慧(AI)的發展正在深刻改變我們的生活方式。從早上起床時的智慧鬧鐘,
到通勤時的路線規劃,再到工作中的各種輔助工具,AI無處不在。
在醫療領域,AI協助醫生進行疾病診斷,提高了診斷的準確率和效率。透過分析
大量的醫療影像和病歷資料,AI能夠發現人眼容易忽略的細節,為患者提供更好
的治療方案。
教育方面,AI個人化學習系統能夠根據每個學生的學習進度和特點,提供客製化
的教學內容。這種因材施教的方式,讓學習變得更加高效和有趣。
然而,AI的快速發展也帶來了一些挑戰。首先是就業問題,許多傳統工作可能會
被AI取代。其次是隱私和安全問題,AI系統需要大量數據來訓練,如何保護個人
隱私成為重要議題。最後是倫理問題,AI的決策過程往往缺乏透明度,可能會產
生偏見或歧視。
面對這些挑戰,我們需要在推動AI發展的同時,建立相應的法律法規和倫理準則。
只有這樣,才能確保AI技術真正為人類福祉服務,創造一個更美好的未來。
"""
    # 傳統方法
    stat_summarizer = StatisticalSummarizer()
    stat_summary = stat_summarizer.summarize(article, ratio=0.3)

    # 現代方法
    ai_summary_result = ai_summarize(article, max_length=120)

    print(f"原文長度：約 {len(article)} 字")
    print(f"原文開頭：{article.strip()[:30]}...")

    print("\n[傳統統計摘要 (關鍵句擷取)]")
    print(stat_summary)

    print("\n[現代 AI 摘要 (生成式)]")
    print(ai_summary_result)

    print("\n* 觀察：傳統摘要是「挑選」，AI 摘要是「創造」。AI 摘要語句連貫性通常更好，但可能產生原文中沒有的內容（在這裡機率較低）。")


# 執行比較
# 依賴於儲存格 1 中的 API_KEY 變數
try:
    if API_KEY and API_KEY != "N/A":
        run_comparison()
    else:
        print("由於 GOOGLE_API_KEY 缺失或無效，僅能執行傳統 NLP 部分的獨立測試")
        # 如果需要，你可以在這裡額外運行一些不依賴 AI 的傳統測試
except NameError:
     print("錯誤：API_KEY 變數尚未在儲存格 1 中定義！請先運行儲存格 1。")