# -*- coding: utf-8 -*-
"""modern_methods.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G3aJZTm8aLbnQNEe6io2XRaot9E24nwk
"""

# B-1:使用 Gemini Pro計算語意相似度
!pip install -q google-generativeai
import google.generativeai as genai

from google.colab import userdata
api_key = userdata.get("GOOGLE_API_KEY")

def ai_similarity(text1, text2, api_key):
    """
    使用 Gemini Pro 模型計算語意相似度 (0-100 分)
    """
    try:
        # 設定 API key
        genai.configure(api_key=api_key)

        # 初始化模型
        model = genai.GenerativeModel("gemini-2.5-flash-lite")

        # Prompt 設計
        prompt = f"""
        請評估以下兩段文字的語意相似度。
        請綜合考慮：
        1. 主題是否相同
        2. 語意重疊程度
        3. 表達觀點是否一致
        請僅輸出一個整數分數（0-100），代表相似度百分比。

        文字1：{text1}
        文字2：{text2}
        """

        # 呼叫 Gemini API
        response = model.generate_content(prompt)

        # 擷取模型輸出
        result = response.text.strip()

        # 嘗試轉換成數字
        score = int(''.join([c for c in result if c.isdigit()]))
        if score > 100: score = 100
        if score < 0: score = 0
        return score

    except Exception as e:
        print(f"發生錯誤:{e}")
        return None

text1 = "人工智慧正在改變世界,機器學習是其核心技術"
text2 = "深度學習推動了人工智慧的發展,特別是在圖像識別領域"
text3 = "今天天氣很好,適合出去運動"
text4 = "機器學習和深度學習都是人工智慧的重要分支"
text5 = "運動有益健康,每天都應該保持運動習慣"

similarity1 = ai_similarity(text1, text2, api_key)
similarity2 = ai_similarity(text1, text3, api_key)
similarity3 = ai_similarity(text1, text4, api_key)
similarity4 = ai_similarity(text1, text5, api_key)
print(f"===語意相似度：{similarity1,similarity2,similarity3,similarity4}")

# B-1:使用OpenAI計算語意相似度
!pip install -q openai
from openai import OpenAI
def ai_similarity(text1, text2, api_key=None):
    """
    使用 OpenAI GPT-4 模型計算語意相似度 (0-100 分)
    """
    from google.colab import userdata
    api_key = userdata.get("OPENAI_API_KEY")

    try:
        # 初始化 client
        client = OpenAI(api_key=api_key)

        # 設計 prompt
        prompt = f"""
        請評估以下兩段文字的語意相似度。
        考慮因素：
        1. 主題是否相關
        2. 語意重疊程度
        3. 表達的觀點是否一致
        請僅回答一個整數（0-100），代表語意相似度百分比。

        文字1：{text1}
        文字2：{text2}
        """

        # 呼叫 GPT 模型
        response = client.chat.completions.create(
            model="gpt-4o-mini",  # 或gpt-4-turbo
            temperature=0.0,
            messages=[
                {"role": "system", "content": "You are a precise text similarity evaluator."},
                {"role": "user", "content": prompt}
            ]
        )
        # 解析結果
        result = response.choices[0].message.content.strip()
        digits = ''.join([c for c in result if c.isdigit()])
        score = int(digits) if digits else 0
        score = max(0, min(score, 100))
        return score

    except Exception as e:
        print(f"發生錯誤: {e}")
        return None

text1 = "人工智慧正在改變世界,機器學習是其核心技術"
text2 = "深度學習推動了人工智慧的發展,特別是在圖像識別領域"
text3 = "今天天氣很好,適合出去運動"
text4 = "機器學習和深度學習都是人工智慧的重要分支"
text5 = "運動有益健康,每天都應該保持運動習慣"

similarity1 = ai_similarity(text1, text2, api_key)
similarity2 = ai_similarity(text1, text3, api_key)
similarity3 = ai_similarity(text1, text4, api_key)
similarity4 = ai_similarity(text1, text5, api_key)
print(f"===語意相似度：{similarity1,similarity2,similarity3,similarity4}")

# B-2:AI文本分類
# 安裝 Google 官方套件
!pip install -q -U google-generativeai
import google.generativeai as genai
import json
import re
from google.colab import userdata
api_key = userdata.get("GOOGLE_API_KEY")

def ai_classify_gemini(text):
    """
    使用 Gemini 2.5 Flash Lite 進行多維度文本分類
    回傳:
    {
        "sentiment": "正面/負面/中性",
        "topic": "主題類別",
        "confidence": 0.95
    }
    """
    prompt = f"""
請閱讀以下文字，判斷它的「情感傾向」與「主題類別」，並給出模型信心值(0~1之間)。

文字：
{text}

請以 JSON 格式回答，鍵名如下：
{{
"sentiment": "正面/負面/中性",
"topic": "主題類別 (例如: 科技、旅遊、美食、運動、娛樂、其他)",
"confidence": 機率值
}}
請只輸出 JSON，不要額外文字。
"""

    model = genai.GenerativeModel("gemini-2.5-flash-lite")
    try:
        response = model.generate_content(prompt)
        result_text = response.text.strip()

        # 去除 ```json 或 ``` 標記
        cleaned = re.sub(r"```json|```", "", result_text).strip()

        # 嘗試解析 JSON
        result = json.loads(cleaned)
        return result

    except json.JSONDecodeError:
        return {"error": "JSON 解析失敗", "raw_output": result_text}
    except Exception as e:
        return {"error": str(e)}

# 測試
samples = [
    "這家餐廳的牛肉麵真的太好吃了,湯頭濃郁,麵條Q彈,下次一定再來!",
    "最新的AI技術突破讓人驚艷,深度學習模型的表現越來越好",
    "這部電影劇情空洞,演技糟糕,完全是浪費時間",
    "每天慢跑5公里,配合適當的重訓,體能進步很多"
]
for i, text in enumerate(samples, 1):
    print(f"\n【文本{i}】{text}")
    print(ai_classify_gemini(text))

!pip install -q google-generativeai
import google.generativeai as genai
from google.colab import userdata
api_key = userdata.get("GOOGLE_API_KEY")

def ai_summarize(text, max_length=100):
    """
    使用 Gemini-2.5-flash-lite 生成自動摘要
    Args:
        text (str): 要摘要的文章
        max_length (int): 最大摘要字數（大約）
    Returns:
        str: 摘要文字
    """
    model = genai.GenerativeModel("gemini-2.5-flash-lite")
    prompt = f"""
請將以下文章摘要成一段流暢、通順的中文文字。
摘要要求：
1. 保留文章關鍵資訊
2. 盡量控制摘要長度約{max_length}個字
3. 語句通順、易讀
文章：
{text}
"""
    try:
        response = model.generate_content(prompt)
        return response.text.strip()
    except Exception as e:
        return f"Error: {str(e)}"

# 測試文章
article = """
人工智慧(AI)的發展正在深刻改變我們的生活方式。從早上起床時的智慧鬧鐘,
到通勤時的路線規劃,再到工作中的各種輔助工具,AI無處不在。
在醫療領域,AI協助醫生進行疾病診斷,提高了診斷的準確率和效率。透過分析
大量的醫療影像和病歷資料,AI能夠發現人眼容易忽略的細節,為患者提供更好
的治療方案。
教育方面,AI個人化學習系統能夠根據每個學生的學習進度和特點,提供客製化
的教學內容。這種因材施教的方式,讓學習變得更加高效和有趣。
然而,AI的快速發展也帶來了一些挑戰。首先是就業問題,許多傳統工作可能會
被AI取代。其次是隱私和安全問題,AI系統需要大量數據來訓練,如何保護個人
隱私成為重要議題。最後是倫理問題,AI的決策過程往往缺乏透明度,可能會產
生偏見或歧視。
面對這些挑戰,我們需要在推動AI發展的同時,建立相應的法律法規和倫理準則。
只有這樣,才能確保AI技術真正為人類福祉服務,創造一個更美好的未來。
"""
# 生成摘要
summary = ai_summarize(article, max_length=150)
print("=== 自動摘要結果 ===")
print(summary)